"""empty message

Revision ID: 222a554ed7f6
Revises: 
Create Date: 2025-11-12 23:59:49.339368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222a554ed7f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=True),
    sa.Column('Username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('Birthdate', sa.Date(), nullable=True),
    sa.Column('Gender', sa.String(length=10), nullable=True),
    sa.Column('Phone', sa.String(length=20), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('StudentID', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('StudentID'),
    sa.UniqueConstraint('Username'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
